version: '3.8'

services:
  web:
    build: .
    command: gunicorn alm.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: alm
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
