FROM ruby:3-alpine

# Install awesome_bot and required dependencies
RUN apk add --no-cache build-base \
    && gem install awesome_bot

WORKDIR /lists

# Create an entrypoint script
COPY scripts/awesome-bot-check.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/awesome-bot-check.sh

ENTRYPOINT ["awesome-bot-check.sh"]
